Home work #1
FreeCourseJava/vv_week01 pull request #1
Opened 2022-06-13 21:03 UTC by ivtcro

please check

2022-06-14 13:26 UTC, tru10b approved these changes
неясно, зачем методы делать private

на работу программ это здесь не повлияет

2022-06-15 14:10 UTC, hyragano requested changes

2022-06-15 14:10 UTC, hyragano commented on src/main/java/Account.java
> +        balance += income;
Что будет если balance будет 2147470000 и income 110000 ?

2022-06-15 15:02 UTC, ivtcro commented on src/main/java/Account.java
> +        balance += income;
функция вернёт некорректный результат - отрицательное значение

2022-06-19 14:16 UTC, ivtcro commented on src/main/java/Account.java
> +        balance += income;
внесены изменения в код для предостврщения int overflow

2022-06-19 14:30 UTC, hyragano commented
> неясно, зачем методы делать private
> 
> на работу программ это здесь не повлияет

Тут есть смысл: делай приватным все что возможно

2022-06-19 14:36 UTC, merged